/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type DataSource = "admin" | "usda" | "user";

export type ElementType = "branded_food" | "nutrient" | "recipe" | "whole_food";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CaloriesBurned {
  day: string;
  kcal: number;
  user_id: number;
}

export interface Element {
  external_id: string | null;
  id: Generated<number>;
  name: string;
  source: DataSource;
  type: ElementType;
}

export interface FoodLog {
  amount: number;
  element_id: number | null;
  id: Generated<number>;
  meal_id: number;
  measure_id: number;
  raw_name: string;
}

export interface FoodName {
  element_id: number;
  embedding: string | null;
  id: Generated<number>;
  is_default: Generated<boolean>;
  locale: string | null;
  name: string;
  rank: Generated<number>;
  user_id: number | null;
}

export interface Link {
  child_id: number;
  parent_id: number;
  ratio: number;
}

export interface Meal {
  id: Generated<number>;
  logged_at: Generated<Timestamp>;
  name: string | null;
  user_id: number;
}

export interface Measure {
  element_id: number | null;
  grams: number;
  id: Generated<number>;
  name: string;
  user_id: number | null;
}

export interface Users {
  daily_targets: Json | null;
  email: string;
  id: Generated<number>;
  name: string;
  tracking_started_on: string | null;
}

export interface DB {
  calories_burned: CaloriesBurned;
  element: Element;
  food_log: FoodLog;
  food_name: FoodName;
  link: Link;
  meal: Meal;
  measure: Measure;
  users: Users;
}
