/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ElementType = "branded_food" | "nutrient" | "recipe" | "whole_food";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Alias {
  element_id: Int8;
  embedding: string | null;
  id: Generated<Int8>;
  locale: string | null;
  name: string;
  user_id: Int8 | null;
}

export interface Element {
  id: Generated<Int8>;
  name: string;
  type: ElementType;
  usda_id: number | null;
  user_id: Int8 | null;
}

export interface Link {
  child_id: Int8;
  parent_id: Int8;
  ratio: number;
}

export interface Log {
  amount: number;
  element_id: Int8 | null;
  id: Generated<Int8>;
  meal_id: Int8;
  raw_name: string;
  unit_id: Int8;
}

export interface Meal {
  id: Generated<Int8>;
  logged_at: Generated<Timestamp>;
  name: string | null;
  user_id: Int8;
}

export interface Unit {
  element_id: Int8 | null;
  grams: number;
  id: Generated<Int8>;
  name: string;
}

export interface Users {
  email: string;
  id: Generated<Int8>;
  name: string;
}

export interface DB {
  alias: Alias;
  element: Element;
  link: Link;
  log: Log;
  meal: Meal;
  unit: Unit;
  users: Users;
}
