/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type DataSource = "admin" | "usda" | "user";

export type ElementType = "branded_food" | "nutrient" | "recipe" | "whole_food";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Element {
  external_id: string | null;
  id: Generated<number>;
  name: string;
  source: DataSource;
  type: ElementType;
}

export interface FoodLog {
  amount: number;
  element_id: number | null;
  id: Generated<number>;
  meal_id: number;
  raw_name: string;
  measure_id: number;
}

export interface FoodName {
  element_id: number;
  embedding: string | null;
  id: Generated<number>;
  locale: string | null;
  name: string;
  user_id: number | null;
}

export interface Link {
  child_id: number;
  parent_id: number;
  ratio: number;
}

export interface Meal {
  id: Generated<number>;
  logged_at: Generated<Timestamp>;
  name: string | null;
  user_id: number;
}

export interface Measure {
  element_id: number | null;
  grams: number;
  id: Generated<number>;
  name: string;
}

export interface Users {
  email: string;
  id: Generated<number>;
  name: string;
}

export interface DB {
  element: Element;
  food_log: FoodLog;
  food_name: FoodName;
  link: Link;
  meal: Meal;
  measure: Measure;
  users: Users;
}
